### ISSUE TITLE
get_sentences incorrectly splits text

### ISSUE THREAD

**Issue by igo** [AssemblyAI/assemblyai-python-sdk#99] opened 2024-11-25 22:15 UTC
Text splitting needs to be more meaningful. For example text "Dr. Feynman used..." is incorrectly split by `get_sentences()` to "Dr." and "Feynman used..."

**Comment by ploeber** [comment] 2024-11-27 10:25
Hi! Thanks for the feedback, I'll forward it to our research/eng team

**Comment by marcusolsson** [comment] 2024-11-27 13:00
Closing as this needs to be handled in the API rather than in the Python SDK.

**Closed as not planned by marcusolsson** 2024-11-27 13:00 UTC

**Comment by igo** [comment] 2024-11-27 20:34
@marcusolsson so is this going to be solved elsewhere?

**Comment by marcusolsson** [comment] 2024-11-28 11:15
We've forwarded the feedback to the team and the issue is being tracked internally. Once addressed it'll work without needing to upgrade the Python package.
